In [1]:
import numpy as np
arr=np.arange(1,10)

In [2]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
arr*arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
arr*2/att

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr/1

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [10]:
0/arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
arr/0

C:\Users\Anbu Nambi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [12]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [13]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [14]:
np.log(1)

0.0

In [17]:
np.cos(1)

0.5403023058681398

In [18]:
np.log(2)

0.6931471805599453

In [24]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])